# @package _global_
dataset:
  coeff: ???

model:
  multi:
    optimizer:
      learning_rate: 0.01
    batch_size: 256
    seq_hidden_units: 16
    br_size: 16
    fc_hidden_units: 32
    dropout_rate: 0.1

  self_positional_encoding:
    max_relative_position: 15

exp:
  weights_ema: True
  alpha: 0.01
  beta: 0.99
  balancing: domain_confusion