# @package _global_
dataset:
  coeff: 0.0

model:
  encoder:
    optimizer:
      learning_rate: 0.001
    batch_size: 64
    seq_hidden_units: 12
    br_size: 18
    fc_hidden_units: 18
    dropout_rate: 0.1

  train_decoder: True
  decoder:
    optimizer:
      learning_rate: 0.001
    batch_size: 256
    br_size: 6
    fc_hidden_units: 3
    dropout_rate: 0.1

exp:
  weights_ema: False
  balancing: grad_reverse