# @package _global_
dataset:
  coeff: 1.0

model:
  encoder:
    optimizer:
      learning_rate: 0.01  # Originally - 0.1, but the gradients are exploding
    batch_size: 64
    seq_hidden_units: 18
    br_size: 18
    fc_hidden_units: 18
    dropout_rate: 0.1

  train_decoder: True
  decoder:
    optimizer:
      learning_rate: 0.001
    batch_size: 1024
    br_size: 18
    fc_hidden_units: 18
    dropout_rate: 0.1

exp:
  weights_ema: False
  balancing: grad_reverse