# @package _global_
dataset:
  coeff: 4.0

model:
  encoder:
    optimizer:
      learning_rate: 0.01
    batch_size: 64
    seq_hidden_units: 24
    br_size: 6
    fc_hidden_units: 24
    dropout_rate: 0.2

  train_decoder: True
  decoder:
    optimizer:
      learning_rate: 0.001
    batch_size: 1024
    br_size: 18
    fc_hidden_units: 72
    dropout_rate: 0.1

exp:
  weights_ema: False
  balancing: grad_reverse